<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DuplicateFileCleanerPro.Infrastructure</AssemblyName>
    <RootNamespace>DuplicateFileCleanerPro.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DuplicateFileCleanerPro.Core\DuplicateFileCleanerPro.Core.csproj" />
  </ItemGroup>
</Project>
