<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <ApplicationManifest>Package.appxmanifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <ProjectReference Include="..\DuplicateFileCleanerPro.Core\DuplicateFileCleanerPro.Core.csproj" />
    <ProjectReference Include="..\DuplicateFileCleanerPro.Infrastructure.Windows\DuplicateFileCleanerPro.Infrastructure.Windows.csproj" />
  </ItemGroup>
</Project>
